### ISSUE TITLE
响应式布局

### ISSUE THREAD

**Issue by Corgile** [itsuki0927/itsuki.cn#4]
大佬，前端页面在手机端支持不是很好捏，有没有进一步完善的计划

**Comment by itsuki0927** [comment]
会支持的，其实在Next12的版本是完美支持的，但是我升级到13后改了一下整体的布局，所以就破坏了响应式布局。
目前我在另外一个仓库重新搭建Next13版本的博客，可以期待一下哈~，不出意外的话，很快就见面啦！！！
